# Default parameters for Eval

# DataParam
dataset: cifar10
data_dir: ./data/cifar10
batch_size: 128
num_workers: 4
num_classes: 10

# AttackParam
attack: pgd
epsilon: 8
step_size: 2
num_steps: 10
restarts: 1
delta_norm: l_inf

# EvalParam
model: resnet
seed: 2024
taskname: BaseAT
device: cuda
ckptname: last.ckpt
